#!/bin/bash

# import the libraries
. quicker

# write yuor code here!

@class MyClass
  @var name
  @var age
  @method getName
  @method getAge
  
  function MyClass::MyClass() {
    echo 'constructor'
    this_name=$1
    this_age=$2
  }
  
  function MyClass::~MyClass() {
    echo 'destructor'
  }
  
  function MyClass::getName() {
    echo "$this_name"
  }
  
  function MyClass::getAge() {
    echo "$this_age"
  }
@end

MyClass main 'kiva' '15'
@delete main
